### ISSUE TITLE
How does Product Details page know about the property "productDetails"?

### ISSUE THREAD

**Issue by ErdemT09** [spiralgo/webclient#7]
![image](https://user-images.githubusercontent.com/63192680/130183203-fe6d2e97-6ed9-41cf-903b-ea2e544e2bf2.png)
https://github.com/spiralgo/webclient/blob/master/src/components/products/ProductDetails.js

Here, this component imports `getProductDetails` as an action.

https://github.com/spiralgo/webclient/blob/master/src/redux/actions/product-detatil-action.js
The  `getProductDetailAction` function here somehow communicates to the reducer [here](https://github.com/spiralgo/webclient/blob/master/src/redux/reducers/product-detail-reducer.js). This is my first problem. How does this happen? 

If I'm not mistaken, this happens so: The `store.js` redux object surrounds the entire app. So, when any actions take place within the components of the app, the store perceives this signal from the app looks up the respective reducer in itself. 
It then creates a global-like variable, for example `productDetails`, but only for all components that were `connect`ed to the processed actions.

Is there something I've gotten wrong or missing?

**Comment by ErdemT09** [comment]
As a side problem: What is the difference between `mapStateToProps` and `mapDispatchToProps`?

For this, the internet apparently has many answers:
https://stackoverflow.com/questions/49994197/mapstatetoprops-vs-mapdispatchtoprops
https://stackoverflow.com/questions/39419237/what-is-mapdispatchtoprops

**Comment by ErdemT09** [comment]
```js
  useEffect(() => {
    props.getProductDetail(title);
  }, []);
```

When the component is re-rendered because of routing, it recalls the action to update the product.

**Comment by altayhunoglu** [comment]
You are right Erdem.
 It is a good question indeed since it is the very essence of what Redux does.
 
I will start from the side question:

-  `mapDispatchToProps` is used to map the functions that we start a Redux process.
 For example `getProductDetail()` is a function, defined in `product-detatil-action.js`
 But we want to use it in `ProductDetails`, so we need to map it to props in order to be able to use it wherever we want.

- `mapStateToProps ` is doing the same thing for the variables rather than the functions.

For a further reading, please refer to: https://react-redux.js.org/using-react-redux/connect-mapdispatch

But in the end, these are like patterns and it is almost enough to know that much.

For the first question, you are absolutely right.
For example, we use `getProductDetail` to start an event to get the detail of any product.
If our imaginary server returns the response successfully, this code dispatch the value of `product` to the `store`:
        
`dispatch(getProductDetailAction(nameProductMap[title]));`

Dispatch is used to update the store with the new values.


For the third question, we can roughly think `useEffect` just similar to the `main` method of a Java class.

**Comment by altayhunoglu** [comment]
By the way, `getProductDetail `is a `thunk` function, it is why a little bit different than the ordinary ones:

https://github.com/reduxjs/redux-thunk

**Comment by altayhunoglu** [comment]
A good explanation for thunk:
https://daveceddia.com/what-is-a-thunk/
